app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),

    # Auth paths
    path('login/', views.login_page, name='login'),
    path('register/', views.register_page, name='register'),
    path('logout/', views.logout_user, name='logout'),

    # Product paths
    path('product/<str:pk>', views.product_page, name='product-page'),
    path('list_product/', views.list_product, name='list-item'),
    path('listings/', views.listings, name='dashboard'),
    path('listings/category/<int:category_id>/', views.listings, name='listings-by-category'),

    # User paths
    path('user/<int:pk>/my-bids/', views.user_bids, name='user-bids'),
    path('user/<int:pk>/my-listings', views.user_listings, name='user-listings'),
    path('my-listings/listing/<int:pk>/archive/', views.archive_listing, name='archive-listing'),
    path('my-listings/listing/<int:pk>/edit/', views.edit_listing, name='edit-listing'),
]

bid4it/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from datetime import timedelta


class User(AbstractUser):
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(unique=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    seller = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    starting_price = models.FloatField(null=True, blank=True)
    image = models.ImageField(default="No_image_available.png")
    created = models.DateTimeField(auto_now_add=True)
    end_date = models.DateTimeField(null=True, blank=True)
    archived = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title

    def set_end_date(self, duration):
        if duration not in [3, 5, 7]:
            raise ValueError("Duration must be 3, 5, or 7 days")
        self.end_date = self.created + timedelta(days=duration)
        self.save()
    
    

class Bid(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='bids')
    item = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='bids')
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return f"User: {self.user}, Item: {self.item}, Amount: {self.amount}"

    

app/templates/product/list_product.html
{% extends "main.html" %}

{% block content %}

<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-8 mx-auto">
                <h1 class="py-2">List your <span class="highlight">Product</span></h1>
                <form class="form" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-floating mb-3">
                        <input name="title" type="text" class="form-control" id="title" placeholder="Product Title">
                        <label for="title">Title</label>
                    </div>
                    <div class="form-floating mb-3">
                        <textarea name="description" class="form-control" id="description" placeholder="Product Description" rows="5"></textarea>
                        <label for="description">Description</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input name="starting_price" type="number" step="0.01" class="form-control" id="starting_price" placeholder="Starting Price">
                        <label for="starting_price">Starting Price</label>
                    </div>
                    <div class="form-group">
                        <label for="id_category">Category</label>
                        <select name="category" class="form-control" id="id_category">
                            {% for category in form.category.field.queryset %}
                                <option value="{{ category.id }}" {% if form.category.value == category.id %}selected{% endif %}>{{ category.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="duration">Auction Duration</label>
                        <select name="duration" class="form-control" id="duration">
                            {% for value, label in form.duration.field.choices %}
                                <option value="{{ value }}" {% if form.duration.value == value %}selected{% endif %}>{{ label }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-check mb-3">
                        <input name="archived" type="checkbox" class="form-check-input" id="archived">
                        <label class="form-check-label" for="archived">Archived</label>
                    </div>
                    <div class="mb-3">
                        <label for="image" class="form-label">Product Image</label>
                        <input name="image" type="file" class="form-control" id="image">
                    </div>
                    <div class="py-4">
                        <button type="submit" class="btn btn-outline-success">List</button>
                        <a class="btn btn-outline-dark" href="{{ request.META.HTTP_REFERER }}">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>




{% endblock content %}

app/templates/product/listings.html
{% extends "main.html" %}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <nav class="col-md-3 col-lg-2 d-md-block bg-light sidebar border-right">
            <div class="position-sticky">
                <ul class="nav flex-column">
                    <li class="nav-item font-weight-bold">
                        <a class="nav-link" href="{% url 'dashboard' %}" id="all-listings" data-category="all">All listings</a>
                        <a class="nav-link" data-bs-toggle="collapse" href="#categoryCollapse" role="button" aria-expanded="false" aria-controls="categoryCollapse">
                            Categories
                        </a>
                        <div class="collapse" id="categoryCollapse">
                            <ul class="nav flex-column ms-3">
                                {% for category in categories %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'listings-by-category' category.id %}" data-category="{{ category.slug }}">{{ category.name }}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-bs-toggle="collapse" href="#filterCollapse" role="button" aria-expanded="false" aria-controls="filterCollapse">
                            Filters
                        </a>
                        <div class="collapse" id="filterCollapse">
                            <ul class="nav flex-column ms-3">
                                <li class="nav-item">
                                    <a class="nav-link" href="#" data-filter="time-left">Time Left</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#" data-filter="recently-added">Recently Added</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#" data-filter="price">Price</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>

        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
            <div class="pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">
                    {% if category %}
                        Listings for {{ category.name }}
                    {% else %}
                        All listings
                    {% endif %}
                </h1>
                <p>We currently have {{ count }} active listings</p>
            </div>

            <div id="product-list">
                {% for product in product_has_bids %}
                <div class="product-card" data-category="{{ product.product.category.slug }}">
                    <img src="{{ product.product.image.url }}" alt="Product Image" class="img-fluid">
                    <div>
                        <a class="product-card-title" href="{% url 'product-page' product.product.id %}">{{ product.product.title }}</a>
                        <div class="product-card-details">
                            Ends on: {{ product.product.end_date|date:"d-m-Y H:ia" }}<br> Current price: 
                            {% if product.highest_bid %}
                                £{{ product.highest_bid|floatformat:2 }}
                            {% else %}
                                £{{ product.starting_price|floatformat:2 }}
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </main>
    </div>
</div>



{% endblock content %}

app/templates/product/product.html
{% extends "main.html" %}
{% load custom_filters %}

{% block content %}

<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <p class="fs-1">{{ product.title }}</p>
            <hr>
            {% if highest_bid %}
                {% if highest_bid.user == request.user %}
                <p>You're currently the highest bidder</p>
                {% endif %}
            {% else %}
            <p>No bids yet.</p>
            {% endif %}
            <div class="col-md-6"> 
                <div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
                    <div class="carousel-item active">
                        <img src="{{ product.image.url }}" class="w-100" alt="...">
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="col-md-10">
                    <h1 class="display-5 fw-bolder">{{ product.name }}</h1>
                    {% if product.end_date < now %}
                    <p>Ended on: {{ product.end_date|date:"Y-m-d H:i" }}</p><br>
                    {% else %}
                    <p>Ends on: {{ product.end_date|date:"Y-m-d H:i" }}</p><br>
                    {% endif %}
                    <div class="fs-5 mb-5">
                        <p>Starting price: £{{ product.starting_price }}</p>
                        <p>Bids: {{ bids_count }}</p>
                        {% if highest_bid %}
                        <p>Current price: £{{ highest_bid.amount }}</p>
                        {% else %}
                        <p>No bids yet</p>
                        {% endif %}
                    </div>
                    <div class="d-flex">
                        {% if product.end_date >= now %}
                            {% if request.user != product.seller %}
                            <form method="post">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-primary">Place Bid</button>
                            </form>
                            {% endif %}
                        {% endif %}
                    </div>
                    {% if messages %}
                    <div class="messages mt-3">
                        {% for message in messages %}
                        <div class="alert {% if message.tags == 'success' %}alert-success{% else %}alert-danger{% endif %}" role="alert">
                            {{ message }}
                        </div>
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="container py-5">
                <div class="card">
                    <div class="card-header">
                        <h2>Description</h2>
                    </div>
                    <div class="card-body">
                        <p class="card-text lead">{{ product.description }}</p>
                    </div>
                </div>
            </div>
            <h2 class="mt-5">Bid History</h2>
            <div class="table-responsive">
                <table class="table table-striped table-bordered mt-3">
                    <thead class="table-dark">
                        <tr>
                            <th scope="col">Bidder</th>
                            <th scope="col">Amount</th>
                            <th scope="col">Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for bid in bids %}
                            <tr>
                                <td>{{ bid.user.username|initials }}</td>
                                <td>£{{ bid.amount }}</td>
                                <td>{{ bid.created }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>           
        </div>
    </div>
</section>



{% endblock content %}